### ISSUE TITLE
Document URI based sources/sinks

### ISSUE THREAD

**Issue by xitep** [seznam/euphoria#10]
How is the URI based source/sink set-up supposed to be working?

- [x] Wiki (usage perspective) ⇒ [Source-Sink-URIs](https://github.com/seznam/euphoria/wiki/Source-Sink-URIs)
- [x] Javadoc (dev perspective) ⇒ #28

**Comment by je-ik** [comment]
I would think that this URI based sources and sink should be completely dropped. I have a feeling it belongs in a different module (euphoria-datamodel) or so. What do you think?

**Comment by xitep** [comment]
i agree, but it still needs to be documented :) the docs can then be moved to/reference the new module. so it wouldn't be lost work.
