### ISSUE TITLE
euphoria-core: timestamp assignment upon early emitting/triggering

### ISSUE THREAD

**Issue by xitep** [seznam/euphoria#118]
We identified certain problems regarding watermark assignment when emitting elements earlier and would like to resolve them. The discussion is captured on #114.

## Current state

When emitting elements, euphoria executors assign an element's window's "max timestamp". The effect of this is that all of the emitted elements do have the _same_ stamp. However, when emitting elements earlier, i.e. before the watermark actually reaches end of the corresponding window. Such elements cause the watermark to grow artificially in downstream operators, thus, unintentionally causing late comers.

## Desired state

The proposed solution is to emit elements _not_ with their window's "max timestamp" but, instead, emit them with the emitting operator's current watermark, i.e. the watermark at which elements are emitted.

* Need to verify this will not break attached windowing
* Need to verify this will not break consecutive window assignment (see [`WindowingTest#consecutiveWindowingTest_ReduceByKey`](https://github.com/seznam/euphoria/blob/master/euphoria-operator-testkit/src/main/java/cz/seznam/euphoria/operator/test/WindowingTest.java#L67))

**Comment by je-ik** [comment]
Resolved by #187
