### ISSUE TITLE
Feature: allow multiple elements to be emitted from ReduceByKey

### ISSUE THREAD

**Issue by je-ik** [seznam/euphoria#121]
Currently, `ReduceByKey` supports only single element to be emitted from the reduce function. We should relax this to support multiple emitted values by adding `reduceBy(UnaryFunctor<Iterable<T>, OUT>)`. The original `reduceBy` will then be just a special case with exactly single emitted value.

**Comment by xitep** [comment]
This looks possible (as you suggested for the non-combining version.) Feel free to submit a PR.
