### ISSUE TITLE
euphoria-core: Consider adding support for side-outputs

### ISSUE THREAD

**Issue by vanekjar** [seznam/euphoria#124]
When we discussed implementation details of counters we came across that they may be implemented as side-output from each operator. Details in issue #31. But it seems side-outputs is more general concept deserving separate issue.

The purpose of this issue is to think about implementing similar concept to Apache Beam [additional outputs](https://beam.apache.org/documentation/programming-guide/#transforms-outputs) or Apache Flink [side outputs](https://ci.apache.org/projects/flink/flink-docs-release-1.3/dev/stream/side_output.html)

According to @je-ik:

We could design a _parallel_ outputs to the main output, by naming them (and therefore construct what looks like counter, but essentially is nothing more than another `Dataset`). The code would then look like this:
```java
  Flow flow = Flow.create();
  Dataset<Integer> input = ...;
  Dataset<Integer> output = FlatMap.of(input)
      .using((in, ctx) -> {
        ctx.collect( /* do whatever transformation of `in` */ );
        ctx.collect("input-elements", 1L);
      })
      .output();
  Dataset<Long> inputElements = flow.getNamedStream("input-elements");
  // now I can do whatever i want with this stream, I can window it as I wish, aggregate by a function
  // of my choice and so on, and finally, persist the dataset where I wish
```
So,
 * in the example above I used strings to identify the corresponding outputs, but of course, it was just an example - this would need to be modified a little to incorporate strong typing of the output `Dataset`s - this goes in the direction of `tags` in the sense of Beam
 * the output would probably be neither keyed nor windowed, it would, ofcourse, carry timestamp
 * the output would be available via the `Flow`
 * the executor can know if an output is not used, because user code has to read it (via `getTaggedStream`)
 * what you do with the output `Dataset` is left on the user code, so you can use it for bussiness logic (joining it with some "main" dataset) or monitoring and debugging (storing it into appropriate sink - e.g. elastic search)

A little modified example, which covers the above topics:
```java
  Flow flow = Flow.create();
  Dataset<Integer> input = ...;
  NamedTag<Long> elementsTag = NamedTag.named("input-elements").typed(Long.class);
  Dataset<Integer> output = FlatMap.of(input)
      .using((in, ctx) -> {
        ctx.collect( /* do whatever transformation of `in` */ );
        ctx.collect(elementsTag, 1L);
      })
      .withNamedTags(elementsTag)
      .output();
  Dataset<Long> inputElements = flow.getTaggedStream(elementsTag);
  // now I can do whatever i want with this stream, I can window it as I wish, aggregate by a function
  // of my choice and so on, and finally, persist the dataset where I wish
```

**Comment by je-ik** [comment]
In roadmap.
