### ISSUE TITLE
[DISCUSS]: stateful operations should have only single storage provider

### ISSUE THREAD

**Issue by je-ik** [seznam/euphoria#128]
Currently, there are possibly multiple storage providers exist for a stateful operator (e.g. RSBK). These include at least (but might not be limited to):
 - the general `StorageProvider` injected into the RSBK operator
 - a `TriggerContext` (which extends the `StorageProvider`) and application code can therefore implement it independently

I think we should force a single implementation of this interface inside the stateful operator by removing the other `StateProvider` implementations and instead of **is a** adopt a **has a** strategy, i.e:
```java
/**
 * A context is given to {@link Trigger} methods to allow them to register
 * timer callbacks.
 */
public interface TriggerContext {

  /**
   * Fire specific trigger on given time.
   * Schedule the given trigger at the given stamp.
   * The trigger will be fired as close to the time as possible.
   *
   * @param stamp the timestamp to register a timer for
   * @param window the window to register the timer for
   *
   * @return {@code true} when trigger was successfully scheduled
   */
  boolean registerTimer(long stamp, Window window);

  /**
   * Delete previously registered timer
   *
   * @param stamp the stamp of a previously registered timer
   * @param window the window of the previously registered timer
   *
   * @see #registerTimer(long, Window)
   */
  void deleteTimer(long stamp, Window window);

  /**
   * @return the current timestamp from runtime (may be different from real
   * clock time).
   */
  long getCurrentTimestamp();

  /**
   * Retrieve associated {@code StorageProvider} of this context.
   * @returns the associated {@code StorageProvider}
   **/
  StateProvider getStateProvider(); 


  /**
   * Extension of {@link TriggerContext} that is given to
   * {@link Trigger#onMerge} as an argument.
   */
  interface TriggerMergeContext extends TriggerContext {
    void mergeStoredState(StorageDescriptor storageDescriptor);
  }

}

```

This issue is to start discussion on the topic to see if we can come to a viable solution.

**Comment by xitep** [comment]
Thanks! What type of problem would this solve? (So far I can see, the new API design could avoid having to modify multiple places if a new method is added to the `StorageProvider` interface, is that what you are aiming at?)

* I'm a bit confused about _"application code"_ ... a `TriggerContext` is always given to application code, i.e. executors provide the implementations, application code merely uses it. Could it be you're building an adapter and therefore have the need to implement `TriggerContext` on your own?
* The API change (e.g. the proposed change on `TriggerContext`) is possible of course. Existing implementations could merely implement the new `getStateProvider` as `return this`. More effort would be with the client side accessing the context (but it still feels like a mechanical change.)

**Comment by je-ik** [comment]
Okay, maybe there is just problem with my interpretation. This discussion is aimed not on the *client* side, but more the *executor* side of the API. When building a new executor, one might get a little confused about "how will the trigger context (which is also a state provider) implement the state provider, and how do I have to care about snapshotting the state in this context?". Maybe this is just a little clarification, that the context **isn't** real context, it just provides some state provider service to triggers. Did I explain the motivation right?

**Comment by xitep** [comment]
thanks! yes, i understand better now. well, as i mentioned the change is possible - at the cost of a slightly longer client code. i don't have a strong opinion about this actually. what about @vanekjar?

**Comment by je-ik** [comment]
Obsolete.
