### ISSUE TITLE
Redesign Dataset#getPartitioning()

### ISSUE THREAD

**Issue by xitep** [seznam/euphoria#16]
The method `Dataset#getPartitioning()` in the client API doesn't make sense in its current form (spotted as part of #15). Partitioners themselves are a property of operators not datasets. However, we still need to preserve the "numPartitions" property available through the `#getPartitioning()` which is used to relay an dataset's physical split further down a flow.

I suggest to change the method to a plain `int Dataset#getNumPartitions()`. A negative value denotes "undefined" just as it is handled so far.

**Comment by je-ik** [comment]
I don't know the details of current implementation, but the original idea behind this was that there are certain operators that preserve partitioning (number of partitions and partitions) - typical example is `FlatMap`. When some other (shuffle) operator gets on input a `Dataset`, it might change its implementation based on the input partitioning. Of course, it can always traverse the DAG and retrieve the partitioning manually.
