### ISSUE TITLE
euphoria-core: generalize flow translation

### ISSUE THREAD

**Issue by xitep** [seznam/euphoria#23]
The spark and flink flow translator use similar structures when translating a user defined flow into an execution graph. The code is more or less duplicated. We shall extract this into an executor independent layer to be used for translation purposes by all executors. See `cz.seznam.euphoria.flink.FlowTranslator` (and `cz.seznam.euphoria.flink.streaming.StreamingFlowTranslator`) and `cz.seznam.euphoria.spark.SparkFlowTranslator`.

**Comment by je-ik** [comment]
Obsolete.
