### ISSUE TITLE
Has some plans supporting Flink SQL ?

### ISSUE THREAD

**Issue by lynchlee** [seznam/euphoria#258]

**Comment by lynchlee** [comment]
@je-ik

**Comment by je-ik** [comment]
Hi @lynchlee, thanks for interest in Euphoria API. Our main goal now is to merge Euphoria with Apache Beam, which could enable what you are looking for via Beam SQL. It is desirable to be able to mix various Beam DSLs with Euphoria API. This is some mid-term goal we are up to right now. Does this answer the question?

**Comment by lynchlee** [comment]
@je-ik got it , thanks.
