### ISSUE TITLE
UnboundedDataSource has no way of reporting stream error

### ISSUE THREAD

**Issue by slechta** [seznam/euphoria#262]
Hi,
I am facing an issue where I have KafkaSource with not yet available broker. The call
`List<UnboundedPartition<T, OFFSET>> getPartitions();` (interface UnboundedDataSource)
returns emptyList instead of reporting an error. There is even a comment in KafkaSource.class line 225:
```
          // ~ FIXME a leader might not be available (check p.leader().id() == -1)
          // ... fail in this situation
```
A stream can fail for a number of reasons. One of them is connection error (in this case kafka broker was starting and was no yet ready which resulted that `List<PartitionInfo> ps = c.partitionsFor(topicId);` returned empty list). Returning an empty list hides the error completely and the operation is successfully completed without any data.

Therefore I propose a change in the UnboundedDataSource interafce. The getPartitions() should throw an checked exception for example PartitionsUnavailableException.

**Comment by je-ik** [comment]
Hi Pavel,
thanks for the issue, would you be interested in participating in PR for this? If yes, would you please open a PR so that we can iterate over this?
Many thanks!

**Comment by slechta** [comment]
Fixed in https://github.com/seznam/euphoria/pull/265
