### ISSUE TITLE
Why it is named as 'HadoopTextFileSource'

### ISSUE THREAD

**Issue by djKooks** [seznam/euphoria#284]
Hello,
this is just a simple question.

While looking sample source, I'm wander why source input class name has 'hadoop' in it because it is just working with local text file.

Could you answer this question?
Also, if there is some kind of chat room to ask simple question like this?

Thanks.

**Comment by dmvk** [comment]
Hi,

the reason it is based on hadoop input format - TextInputFormat, which is designed primarily with HDFS but can work with local files as well.

You're welcome to join the ASF slack - https://s.apache.org/slack-invite and we'll invite you to beam-euphoria channel as we are currently in process of migration our codebase into Apache Beam.

Thanks,
D.

D.
