### ISSUE TITLE
euphoria-core: generic FlowBuilder

### ISSUE THREAD

**Issue by xitep** [seznam/euphoria#36]
Right now, running a (single) flow requires the programmer to write the usual class with a main method, setting up the executor, submitting her flows to it and executing it. This is a lot of boilerplate in the way of getting a flow to execute. Ideally, we'd be able to say:

```bash
spark-submit [parameters] --class cz.seznam.euphoria.spark.runner.Runner --jars usercode.jar euphoria-assembly.jar [name of class providing the flow to executed; located in the provided jars]
```

The rough idea is to have each executor providing a convenience `Runner` being able to take a class (by name), instantiate it, and then derive a flow from it to execute. Actually, a lot of the "runner" code is expected to be the same across different executors, thus, we want to abstract the process into `euphoria-core`. The named, user provided class will need to implement a common interface, through which the abstraction will create the flow to execute; `FlowBuilder` seems like a good name.

**Comment by je-ik** [comment]
Obsolete.
