### ISSUE TITLE
euphoria-flink: streaming word-count with time-sliding very slow

### ISSUE THREAD

**Issue by xitep** [seznam/euphoria#47]
Executing a word-count like program - this is the simplest scenario to trace down the problem - against an Euphoria's Flink Streaming executor using `TimeSliding` windowing, reveals a huge shuffle overhead compared to an implementation of the same program using Flink's native Java API.

### Experiment characteristics

* Apart from the key, the actual "values" being shuffled (as intended by the programmer) are actually small (in both cases):
  * On native flink: it's a word (string)
  * On euphoria: it's just a long (the value to be reduced)
* TimeSliding; the more windows the bigger Euphoria's overhead

### Problem

Euphoria tries to implement a strategy such that the size of the actual values being shuffled gets reduced. This is, instead of shuffling RBK's (and RSBK's) original input elements, before the shuffle phase it extracts the "values" (to be later reduced) and sends those for reduction (instead of the original input elements). The reasoning behind this choice is to send the typically smaller values instead of the bigger input elements. However, due to windowing being applied to the operator's original input elements, it also needs to extract the original input elements' windows before sending them together with the value across the wire. The more windows there are for a single value, the bigger the overhead of data being shuffled.

The more data is being shuffled, the quicker network buffers get filled, which can lead to back pressure, thereby making the consumer side go slower. (To mitigate against back pressure, we can resize the network buffers at the cost of memory consumption.)

Our implementation of the idea to shuffle only values instead of the original input elements suffers under the following items:
* If the "value" being shuffled isn't smaller than or equal size as the original input element, we're immediately introducing unnecessary overhead.
* If the "value" being shuffled _plus_ the necessary window information for the element isn't smaller than or equals size as the original input element, we're introducing unnecessary overhead. (note: this problem is not relevant when considering a partitioning schema by "window and key"; this is a potential but not-yet-implemented/explored reduce-by-key strategy.)
* Users of the Euphoria API have no chance to express a preference for a particular strategy in regards to the shuffle.

### What's to do next

- [x] Attempt to reduce the serialized size of window types natively provided by Euphoria
  * @vanekjar had a very nice idea about optimizing the `TimeSliding` windowing use-case: instead of creating many physical objects for each `TimeInterval` of the time slides, i.e. a `HashSet<TimeInterval>`, create one object which is able to lazily expand itself into these many window objects only when they are iterated - which for the RBK happens after the shuffle. the serialized form of such a "set of windows" can be of constant size independent of the number of windows presented
- [x] Declare what is good enough for us, i.e. it's fine to say "we don't care about word-count like reductions" and not further bother with the problem
- [x] Depending on the previous item, find a way to hint the executor for an alternative shuffle strategy (this doesn't necessarily have to be an easy-to-use feature, but it shall be possible.)

### Conclusion

It is unclear whether the strategy currently implemented by Euphoria's streaming Flink executor is sufficient for most common use-cases. At best, we can say the strategy is not flexible to support use-cases where the original input element's size is not significantly different that the "value" being reduced. Further, from an API perspective users are not able to optimize for such use-cases (whereas users can optimize the opposite use-case in the Flink API - basically users of the Flink API can implement what Euphoria's streaming Flink executor does.)

Last but not least, the problem of this "reduce-by-key" strategy as detailed above, explains a significant part of the overhead measured under #14, which uses a benchmark with a "word-count" like reduction using `TimeSliding`.

**Comment by je-ik** [comment]
Very nice explanation of the problem, @xitep. Is there any chance to recognize what shuffle strategy to use during runtime? I think that it could be possible, but I'm not sure if it is worth the complications it would bring into the implementation. In my point of view, a very simple solution would be not to apply to value-mapper before shuffle.

Is there any chance we could measure the impact of such a "simple" change?

**Comment by xitep** [comment]
The impact is considerable, of course! I just "hacked" the RBK to do windowing after the shuffle (see branch `pete/flink-streaming-performance-experiments`) and could reduce the execution time of the mentioned `TimeSliding` benchmark from ~40m down to ~25m. The amount of shuffle data went down from ~19.3GB to ~2.3GB (the `TimeSliding` windowing in this benchmark sets up 24 windows per element). (just for comparison: the same, native flink program executes in ~15minutes with 1.65GB shuffled data.)

In a test with `Time` windowing (i.e. always one window per element), I could see the amount of shuffled data going down from 4.2GB to (the expected) 2.3GB. However, I could not see any significant improvement to the execution time. This is more or less expected as the bottleneck with the `TimeSliding` windowing was introduced by the back-pressure due to filling network buffers too quickly. (just for comparison: the same, native flink program executes in ~15m with 1.65GB shuffled data; actually the same as with `TimeSliding`.)

**Comment by je-ik** [comment]
That sounds to me like it would be beneficial to completely drop the value mapper before shuffle phase and to just shuffle the original elements. What do you think?

**Comment by vanekjar** [comment]
I would disagree with the latest idea of dropping the _value mapper_ completely. When the _value mapper_ is used there is great chance of element size reduction in most cases - it's some kind of field extraction or even remapping element to just a number (in case of word count).

My proposed solution would be:

* Optimize the serialized size of `Set<Window>` which is shuffled along with each element. No need to shuffle all `TimeInterval` elements with time sliding windowing. These can be recomputed lazily just from 3 numbers `startTime`, `endTime`, `slideSize` as mentioned in the original description.

* Don't enforce the usage of  _value mappers_ in API builders. Usage of `valueBy` should be optional and considered as identity function by default.

* When the default _value mapper_ is used the runtime can decide to optimize and not to extract the window set before shuffle. Since the _value mapper_ is identity in this case, windows can be extracted later after the shuffle.

**Comment by je-ik** [comment]
The problem of this is that is all sounds like a classical premature optimization. There are many other questions that arise:
 * what about situations where user supplies user-defined windowing that emits large number of windows - there is no systematic way to overcome the performance drop in that case
 * AFAIK the `valueBy` is optional (or is intended to be), exactly as you write
 * when user specifies `valueBy` it is not because of the optimization, but because it is beneficial for the downstream processing - the function **has to be applied**, but the runtime can figure out where

If the value mapper is applied consistently after the shuffle, then the user can code the optimization himself - first do the value mapping in a separate `MapElements` operator and only after that do the stateful aggregation, which solves the problem for him. If euphoria executor does this optimization automatically, the user cannot do anything to *prevent* it.

**Comment by xitep** [comment]
i think, it's not that easy, unfortunately.

attached windowing forces us to transfer windows along the elements. hence, in more complicated programs, i.e. programs with two or more stateful operators in a flow, the savings of _applying `valueBy`  only after shuffle_ are only clear to estimate for the _very first_ stateful operator (with an explicit windowing strategy defined) consuming a "not yet windowed" dataset. followers of this first stateful operator have then to forward the original window further down the channel for the potentially next window assignment function. if there's a shuffle in between, we'll again be transferring windows.

to minimize the overhead of transferring windows or to avoid it entirely where it is not necessary, a flow specific analysis and translation of the DAG as a whole would be necessary. i don't think we can get away with translating operators one by one independently of each other to end up with a relatively straight forward translation layer while keeping the overhead small.

**Comment by je-ik** [comment]
I agree, when it comes to attached windowing, then there is no other option than to (somehow) transfer the windows with the data. BUT, when user uses attached windowing, then the window label becomes **part of the data** itself (from a practical point of view), so the upper definition holds, windowing is still applied after the shuffle.

The question of minimizing the shuffle data then boils down to providing a way of crunching multiple windows into a single serialized data object. I can imagine that this would be a user supplied function. One of the implementations for sliding time windows could be as you have suggested. Nevertheless, it seems to me better not to do any stuff that is not obvious to the user and that he cannot control. At lease until there is some sort of deeper DAG analysis as you suggest.

**Comment by xitep** [comment]
closing this issue with the following remarks to re-act on all points we wanted to look at:

* #66 introduced a remedy against the huge overhead per item on time-sliding windowing (or potentially other windowing strategies)
* as of #53 users are able to hint the flink streaming executor to extract the value after shuffle
* and, yes, we do care about word-count-like programs :) after all, they are actually not that rare
