### ISSUE TITLE
make builds faster

### ISSUE THREAD

**Issue by xitep** [seznam/euphoria#48]
Would it be possible to speed up `mvn install` for local development? It'd be great if I was able to turn off javadoc, findbugs, and possibly other build steps when developing locally. Maybe we can provide different  profiles such that we can opt out of certain build steps using `mvn install -P-xyz` when building interactively on the command line.

**Comment by vanekjar** [comment]
That's a great idea!
I was struggling with exactly same problem yesterday. Tried to build some experiment version with my changes and I spent a couple of minutes waiting for the build just to find out I was missing license header.
