### ISSUE TITLE
Compare performance with Apache Beam

### ISSUE THREAD

**Issue by xitep** [seznam/euphoria#54]
It'd be good to evaluate how Euphoria compares with [Apache Beam](https://beam.apache.org/) in terms of performance on Apache Spark as well as on Apache Flink. Similarly to #11, we'd like to measure the overhead of the Beam layer of the benchmark program compared to a raw flink and spark impl and see how that overhead differs from Euphoria's overhead.

1. This can reveal either problems on our side or problems on the side of Apache Beam, which we can report back.
2. This will provide a good base for deciding whether its worth to start with #32 or rather postpone it.
3. We'll have some concrete numbers for upcoming presentations about Euphoria. (Questions regarding _"Euphoria vs. Beam"_ are expected and the overhead comparison is at least one point of interest.)

A very premature observation on a word-count like program suggests that Apache Beam 0.6.0 on Flink 1.2 might be well suffering from expanding windows before the shuffle (see #47.)

**Comment by horkyada** [comment]
It seems that Beam is unable to perform join on windowed inputs with different windowings. It is stated in here https://cloud.google.com/dataflow/model/group-by-key
```
When using CoGroupByKey to group PCollections that have a windowing strategy applied, all of the PCollections you want to group must use the same windowing strategy and window sizing. For example, all the collections you're merging must use (hypothetically) identical 5-minute fixed windows or 4-minute sliding windows starting every 30 seconds.

If your pipeline attempts to use CoGroupByKey to merge PCollections with incompatible windows, Dataflow will generate an IllegalStateException error when your pipeline is constructed.
```
and it corresponds to the code in Beam where compatibility of windows is only reduced to equality check in `SlidingWindows` as well as in `FixedWindows`. It causes IllegalStateexception 
```java
Exception in thread "main" java.lang.IllegalStateException: Inputs to Flatten had incompatible window windowFns: org.apache.beam.sdk.transforms.windowing.SlidingWindows@3b23cf, org.apache.beam.sdk.transforms.windowing.FixedWindows@f5f1
```
We can omit the Beam windowing and simulate the windows by custom data, but that is probably not the intent of this ticket.
Otherwise we have to redefine the benchmark or just create a different one.

**Comment by horkyada** [comment]
I performed the batch benchmark without beam windowing with transmitting only window-end times as `long`s (same as in pure Spark/Flink batch programs). The results are:
 - beam-spark (batch): 2.1h
 - beam-flink (batch): 1.5h

For context:
 - euphoria-spark (batch): 1.1h
 - euphoria-flink (batch): ? (6h)

**Comment by je-ik** [comment]
I think we can obsolete this.
