### ISSUE TITLE
Build fails when invoked from subproject

### ISSUE THREAD

**Issue by je-ik** [seznam/euphoria#90]
When the build is invoked from subproject (e.g. `mvn install` from `euphoria-core` subdirectory) the build fails due to invalid reference to `license-header.txt`.

**Comment by xitep** [comment]
I'm afraid I have no fix for this; as a work-around you can use `mvn install -Dlicense.header=../license-header.txt` or more conveniently `mvn install -P-regular-build` during local development.

**Comment by je-ik** [comment]
I didn't dig into this, but it isn't possible to reference the file via maven variables, something like `src_dir`, or something like this (I'm just guessing :)).

**Comment by je-ik** [comment]
Fixed by symlonks.
