### ISSUE TITLE
Output partitioning of Union operator is not well defined

### ISSUE THREAD

**Issue by je-ik** [seznam/euphoria#92]
Number of output partitions (as reflected by `Dataset#getNumPartitions()`) of `Union` operator should probably be one of the following:
 a) sum of partitions of input `Dataset`s
 b) maximum of number of input partitions over input Dataset

Currently, it seems that the partitioning is taken from the first input `Dataset`, which seems to be wrong. I'm not 100% sure about the consequences of changing the semantics, so I'm leaving this for a discussion under this issue.

**Comment by je-ik** [comment]
I'd prefer as a solution either `b)`, or even better a way that executor could supply this logic. In some executors is might be preferable to go with option `a)`, because it might be more effective (in fact that makes operator `Union` just a "meta" operator over partitioning).

**Comment by vanekjar** [comment]
Yes, this is a definitely a bug. Actually we're not relying on `Dataset#getNumPartitions` method in our executor code (as far as I know), we rather work with partitioners and partitioning directly. This method is intended to be used in the user code to obtain information about current parallelism.

Anyway I would prefer the option `b)` as well. It seems to be more safe.

**Comment by je-ik** [comment]
The problem here is that `Union` operator has no partitioner. It would be nice if we consolidate the `Dataset#getNumPartitions` so that it would reliable. Thinking about his again I think the following code should work consistently independently of the executor:
```java
  Dataset<...> first = ...;
  Dataset<...> second = ...;
  Dataset<...> union = Union.of(first, second).output();
  ReduceByKey.of(union)
     ....
     .setPartitoner(...)
     .output()
     .persist(...);
```
The number of output partitions in such a case (where a partitioner is defined, but number of partitions is not) should not depend on the executor, but only on number of input partitions.

**Comment by xitep** [comment]
Yes, the semantics regarding the number of partitions are undefined yet. Thanks for the ticket! In this example ...

```java
Dataset<...> one = ...;
Dataset<...> two = ...;
Dataset<...> union = Union.of(first, second).output();
MapElements.of(union).using(...).output().persist(...);
```

... I'd intuitively expect `union.numPartitions() == one.numPartitions() + two.numPartitions()`. however, this _sum_ doesn't make much sense to me when there's a stateful operator consuming the union. in fact, i'd expect the stateful operator to take advantage of all _available_ (but no more than that) resources by default unless the user constraints it explicitly using `setNumPartitions`.

**Comment by je-ik** [comment]
@xitep Hm, that's actually a great example, which clarifies the problem really well. I think that your intuition is actually great, and we should stick with it. It clearly defines postconditions of `Union`, in the sense that total number of partitions SHOULD be equal to sum of number of input partitions. This should hold for both stateful and stateless operators, therefore in the example above with `ReduceByKey`, the total number of partitions should be fixed to this sum as well. Could we add this check to `euphoria-operator-testkit`?

**Comment by xitep** [comment]
as part of #96 we concluded to leave the default partitioning of the `Union` (as well as the `Join`) operator intentionally undefined (on the level of `euphoria-core`), so that executors may choose on their own the best possible option. further, we may consider dropping `Dataset#getNumPartitions()`. more details on the mentioned pr.

**Comment by je-ik** [comment]
Obsoleted via #160
