### ISSUE TITLE
Consider aligning naming of "batch windowing"

### ISSUE THREAD

**Issue by xitep** [seznam/euphoria#95]
Apache Beam as well as Apache Flink refer to what we named `Batch` and `Batch.BatchWindow` as `GlobalWindows` and `GlobalWindow` respectively. I think the term "global" makes more sense. 1) Windowing is a separate concept/value to "batch/stream processing". 2) By aligning the names we create less confusion for new users.

In particular, I'd like to propose renaming:

* `Batch` => `GlobalWindowing`
* `Batch.BatchWindow` => `GlobalWindowing.GlobalWindow` or just `GlobalWindowing.Window`

Please comment if renaming doesn't make sense to you.

**Comment by je-ik** [comment]
+1
A little remark about the relationship between the windowing and batch/streaming processing - the batch or global windowing makes no sense in case of stream processing, so maybe this a little better guides the user about when to use it, but I agree that this is just a little difference and the term global window might play the same role as well.

**Comment by xitep** [comment]
i agree, "global windowing" doesn't make sense on streams. maybe an "early triggered global window on streams" (which we do not support at the moment) could find a (limited) use-case, though, i see it rather problematic in regards to the ever growing window state and key base.
